package com.example.kotlin_recyclerview

class Data {

    val dataTram = arrayListOf<Transport>(
        Transport( "https://mobile.ettu.ru/station/1168",  "1-й км (на Пионерскую)",  "1-й км",  "Первый километр"),
        Transport( "https://mobile.ettu.ru/station/1169",  "1-й км (на Техучилище)",  "1-й км",  "Первый километр"),
        Transport( "https://mobile.ettu.ru/station/3497",  "40 лет ВЛКСМ",  "40 лет ВЛКСМ",  "Сорок лет ВЛКСМ"),
        Transport( "https://mobile.ettu.ru/station/1170",  "40 лет Октября (на Диагностический центр)",  "40 лет Октября",  "Сорок лет Октября"),
        Transport( "https://mobile.ettu.ru/station/1171",  "40 лет Октября (на ст. Машиностроителей)",  "40 лет Октября",  "Сорок лет Октября"),
        Transport( "https://mobile.ettu.ru/station/3498",  "7 Ключей",  "7 Ключей",  "Семь Ключей"),
        Transport( "https://mobile.ettu.ru/station/4007",  "Автовокзал (на Фрунзе)",  "Автовокзал",  "Автовокзал"),
        Transport( "https://mobile.ettu.ru/station/4008",  "Автовокзал (на Южную)",  "Автовокзал",  "Автовокзал"),
        Transport( "https://mobile.ettu.ru/station/3316",  "Автомагистральная (на Пехотинцев)",  "Автомагистральная",  "Автомагистральная"),
        Transport( "https://mobile.ettu.ru/station/3317",  "Автомагистральная (на Сварщиков)",  "Автомагистральная",  "Автомагистральная"),
        Transport( "https://mobile.ettu.ru/station/3362",  "Академия при Президенте России (на Большакова)",  "Академия при Пр. РФ",  "Академия при Пр. РФ"),
        Transport( "https://mobile.ettu.ru/station/3363",  "Академия при Президенте России (на Цирк)",  "Академия при Пр. РФ",  "Академия при Пр. РФ"),
        Transport( "https://mobile.ettu.ru/station/3819",  "Бажова (на Восточную)",  "Бажова",  "Бажова"),
        Transport( "https://mobile.ettu.ru/station/3825",  "Бажова (на гост. Исеть, Оперный театр, Дом Кино)",  "Бажова",  "Бажова"),
        Transport( "https://mobile.ettu.ru/station/3436",  "Бакинских Комиссаров (на Уральских Рабочих)",  "Бакинских Комиссаров",  "Бакинских Комиссаров"),
        Transport( "https://mobile.ettu.ru/station/3437",  "Бакинских Комиссаров (на Победы)",  "Бакинских Комиссаров",  "Бакинских Комиссаров"),
        Transport( "https://mobile.ettu.ru/station/4369",  "Бебеля (на Пехотинцев)",  "Бебеля",  "Бебеля"),
        Transport( "https://mobile.ettu.ru/station/4370",  "Бебеля (на Таганский ряд)",  "Бебеля",  "*"),
        Transport( "https://mobile.ettu.ru/station/3320",  "Белинского (на Дом художника)",  "Белинского",  "*"),
        Transport( "https://mobile.ettu.ru/station/3321",  "Белинского (на Цирк)",  "Белинского",  "*"),
        Transport( "https://mobile.ettu.ru/station/3322",  "Белореченская (на Волгоградскую)",  "Белореченская",  "*"),
        Transport( "https://mobile.ettu.ru/station/3323",  "Белореченская (на Московскую)",  "Белореченская",  "*"),
        Transport( "https://mobile.ettu.ru/station/4162",  "Библиотека (на Донбасскую)",  "Библиотека",  "*"),
        Transport( "https://mobile.ettu.ru/station/4173",  "Библиотека (на Лукиных)",  "Библиотека",  "*"),
        Transport( "https://mobile.ettu.ru/station/3324",  "Блюхера (на ст.Шарташ)",  "Блюхера",  "*"),
        Transport( "https://mobile.ettu.ru/station/3325",  "Блюхера (с Мира на Уральский федеральный университет)",  "Блюхера",  "*"),
        Transport( "https://mobile.ettu.ru/station/3326",  "Блюхера (с Советской на Уральский федеральный университет)",  "Блюхера",  "*"),
        Transport( "https://mobile.ettu.ru/station/3327",  "Блюхера (на Пионерскую)",  "Блюхера",  "*"),
        Transport( "https://mobile.ettu.ru/station/3328",  "Большакова (на Академию при Президенте России)",  "Большакова",  "*"),
        Transport( "https://mobile.ettu.ru/station/3329",  "Большакова (на Фрунзе)",  "Большакова",  "*"),
        Transport( "https://mobile.ettu.ru/station/963627",  "Б-р Малахова (на Фучика)",  "Б-р Малахова",  "Малахова"),
        Transport( "https://mobile.ettu.ru/station/963630",  "Б-р Малахова (на ст. м. Ботаническая)",  "Б-р Малахова",  "Малахова"),
        Transport( "https://mobile.ettu.ru/station/4307",  "Братская (на Сухоложскую)",  "Братская",  "*"),
        Transport( "https://mobile.ettu.ru/station/4308",  "Братская (на Завод РТИ)",  "Братская",  "*"),
        Transport( "https://mobile.ettu.ru/station/4276",  "Ватутина (на ст. 7 Ключей)",  "Ватутина",  "*"),
        Transport( "https://mobile.ettu.ru/station/4279",  "Ватутина (на Таганский ряд)",  "Ватутина",  "*"),
        Transport( "https://mobile.ettu.ru/station/3332",  "Верх-Исетский б-р (на Крылова)",  "Верх-Исетский б-р",  "Верх Исетский б-р"),
        Transport( "https://mobile.ettu.ru/station/3333",  "Верх-Исетский б-р (на Дворец Молодежи)",  "Верх-Исетский б-р",  "Верх Исетский б-р"),
        Transport( "https://mobile.ettu.ru/station/4118",  "Верх-Исетский рынок (на Таганский ряд)",  "Верх-Исетский рынок",  "Верх Исетский рынок"),
        Transport( "https://mobile.ettu.ru/station/4119",  "Верх-Исетский рынок (на Колмогорова)",  "Верх-Исетский рынок",  "Верх Исетский рынок"),
        Transport( "https://mobile.ettu.ru/station/963737",  "Вечный Огонь (на Мельникова)",  "Вечный Огонь",  "*"),
        Transport( "https://mobile.ettu.ru/station/963738",  "Вечный Огонь (на пл. Коммунаров)",  "Вечный Огонь",  "*"),
        Transport( "https://mobile.ettu.ru/station/3499",  "ВИЗ",  "ВИЗ",  "*"),
        Transport( "https://mobile.ettu.ru/station/3336",  "Викулова (на Волгоградскую)",  "Викулова",  "*"),
        Transport( "https://mobile.ettu.ru/station/3337",  "Викулова (на ст. ВИЗ)",  "Викулова",  "*"),
        Transport( "https://mobile.ettu.ru/station/3338",  "Войкова (на ст. Фрезеровщиков)",  "Войкова",  "*"),
        Transport( "https://mobile.ettu.ru/station/3339",  "Войкова (на Энтузиастов)",  "Войкова",  "*"),
        Transport( "https://mobile.ettu.ru/station/3495",  "Волгоградская",  "Волгоградская",  "*"),
        Transport( "https://mobile.ettu.ru/station/961847",  "Волгоградская (на ТК Буревестник)",  "Волгоградская",  "*"),
        Transport( "https://mobile.ettu.ru/station/961848",  "Волгоградская (на Серафимы Дерябиной)",  "Волгоградская",  "*"),
        Transport( "https://mobile.ettu.ru/station/3344",  "Ворошиловская (на Фронтовых Бригад)",  "Ворошиловская",  "*"),
        Transport( "https://mobile.ettu.ru/station/3345",  "Ворошиловская (на Электриков)",  "Ворошиловская",  "*"),
        Transport( "https://mobile.ettu.ru/station/3820",  "Восточная (на Уральский федеральный университет)",  "Восточная",  "*"),
        Transport( "https://mobile.ettu.ru/station/3823",  "Восточная (на Бажова)",  "Восточная",  "*"),
        Transport( "https://mobile.ettu.ru/station/4269",  "Вторчермет",  "Вторчермет",  "*"),
        Transport( "https://mobile.ettu.ru/station/3350",  "Гагарина (на Профессорскую)",  "Гагарина",  "*"),
        Transport( "https://mobile.ettu.ru/station/3351",  "Гагарина (на Уральский федеральный университет)",  "УрФУ",  "*"),
        Transport( "https://mobile.ettu.ru/station/3348",  "Гост. Исеть (на Шарташскую)",  "Гост. Исеть",  "Гостинеца Исеть"),
        Transport( "https://mobile.ettu.ru/station/3349",  "Гост. Исеть (на Бажова, Дом Кино, Оперный театр)",  "Гост. Исеть",  "Гостинеца Исеть"),
        Transport( "https://mobile.ettu.ru/station/3352",  "Гурзуфская (на Волгоградскую)",  "Гурзуфская",  "*"),
        Transport( "https://mobile.ettu.ru/station/3353",  "Гурзуфская (на Московскую)",  "Гурзуфская",  "*"),
        Transport( "https://mobile.ettu.ru/station/3361",  "Дворец Молодежи (на Верх-Исетский б-р)",  "Дворец Молодежи",  "*"),
        Transport( "https://mobile.ettu.ru/station/963743",  "Дворец Молодежи (на пл.Коммунаров, Шейнкмана)",  "Дворец Молодежи",  "*"),
        Transport( "https://mobile.ettu.ru/station/3360",  "Дворец Спорта",  "Дворец Спорта",  "*"),
        Transport( "https://mobile.ettu.ru/station/3364",  "Декабристов (на Дом художника)",  "Декабристов",  "*"),
        Transport( "https://mobile.ettu.ru/station/3365",  "Декабристов (на пл. Обороны)",  "Декабристов",  "*"),
        Transport( "https://mobile.ettu.ru/station/3314",  "Диагностический центр (на 40 лет Октября)",  "Диагностический центр",  "*"),
        Transport( "https://mobile.ettu.ru/station/3315",  "Диагностический центр (на Лукиных)",  "Диагностический центр",  "*"),
        Transport( "https://mobile.ettu.ru/station/4272",  "ДК ВОС (на ст. 7 Ключей)",  "ДК ВОС",  "Дворец культуры ВОС"),
        Transport( "https://mobile.ettu.ru/station/4275",  "ДК ВОС (на Таганский ряд)",  "ДК ВОС",  "Дворец культуры ВОС"),
        Transport( "https://mobile.ettu.ru/station/3354",  "ДК им. Лаврова (на Ильича)",  "ДК им. Лаврова",  "Дворец Культуры имени Лаврова"),
        Transport( "https://mobile.ettu.ru/station/3355",  "ДК им. Лаврова (на Кузнецова)",  "ДК им. Лаврова",  "Дворец Культуры имени Лаврова"),
        Transport( "https://mobile.ettu.ru/station/3366",  "Дом Кино (на Киностудию)",  "Дом Кино",  "*"),
        Transport( "https://mobile.ettu.ru/station/3367",  "Дом Кино (на Дом художника)",  "Дом Кино",  "*"),
        Transport( "https://mobile.ettu.ru/station/3396",  "Дом художника (на Дом Кино)",  "Дом художника",  "*"),
        Transport( "https://mobile.ettu.ru/station/3397",  "Дом художника (на Декабристов)",  "Дом художника",  "*"),
        Transport( "https://mobile.ettu.ru/station/3398",  "Дом художника (с Декабристов на Цирк)",  "Дом художника",  "*"),
        Transport( "https://mobile.ettu.ru/station/3399",  "Дом художника (с Дома Кино на Цирк)",  "Дом художника",  "*"),
        Transport( "https://mobile.ettu.ru/station/4163",  "Донбасская (на Кировградскую)",  "Донбасская",  "*"),
        Transport( "https://mobile.ettu.ru/station/4172",  "Донбасская (на Библиотеку)",  "Донбасская",  "*"),
        Transport( "https://mobile.ettu.ru/station/3736",  "Донская (на ст. Эльмаш)",  "Донская",  "*"),
        Transport( "https://mobile.ettu.ru/station/4238",  "Донская (на Энтузиастов)",  "Донская",  "*"),
        Transport( "https://mobile.ettu.ru/station/4286",  "Дружининская (на Таганский ряд)",  "Дружининская",  "*"),
        Transport( "https://mobile.ettu.ru/station/4287",  "Дружининская (на ст. 7 Ключей)",  "Дружининская",  "*"),
        Transport( "https://mobile.ettu.ru/station/1172",  "Ельцина (на Управление дороги)",  "Ельцина",  "*"),
        Transport( "https://mobile.ettu.ru/station/1173",  "Ельцина (на Папанина)",  "Ельцина",  "*"),
        Transport( "https://mobile.ettu.ru/station/3340",  "Ж/д вокзал (на Управление дороги)",  "Ж/д вокзал",  "Жд вокзал"),
        Transport( "https://mobile.ettu.ru/station/3341",  "Ж/д вокзал (на Челюскинцев, Пионерскую)",  "Ж/д вокзал",  "Жд вокзал"),
        Transport( "https://mobile.ettu.ru/station/4025",  "Завод РТИ (на Братскую)",  "Завод РТИ",  "*"),
        Transport( "https://mobile.ettu.ru/station/4026",  "Завод РТИ (на пер. Рижский)",  "Завод РТИ",  "*"),
        Transport( "https://mobile.ettu.ru/station/3368",  "Заводская (на Красноуральскую)",  "Заводская",  "*"),
        Transport( "https://mobile.ettu.ru/station/3369",  "Заводская (на Татищева)",  "Заводская",  "*"),
        Transport( "https://mobile.ettu.ru/station/4062",  "Зеленый остров",  "Зеленый остров",  "*"),
        Transport( "https://mobile.ettu.ru/station/3370",  "Ильича (на ДК им. Лаврова)",  "Ильича",  "*"),
        Transport( "https://mobile.ettu.ru/station/3371",  "Ильича (на Индустрии)",  "Ильича",  "*"),
        Transport( "https://mobile.ettu.ru/station/3372",  "Индустрии (на Ильича)",  "Индустрии",  "*"),
        Transport( "https://mobile.ettu.ru/station/3373",  "Индустрии (на Победы)",  "Индустрии",  "*"),
        Transport( "https://mobile.ettu.ru/station/3378",  "Калининская (на Педагогический университет)",  "Калининская",  "*"),
        Transport( "https://mobile.ettu.ru/station/3379",  "Калининская (на Техучилище)",  "Калининская",  "*"),
        Transport( "https://mobile.ettu.ru/station/3380",  "Каменные Палатки (на Комсомольскую)",  "Каменные Палатки",  "*"),
        Transport( "https://mobile.ettu.ru/station/3381",  "Каменные Палатки (на Новгородцевой)",  "Каменные Палатки",  "*"),
        Transport( "https://mobile.ettu.ru/station/4268",  "Керамическая",  "Керамическая",  "*"),
        Transport( "https://mobile.ettu.ru/station/3382",  "Киностудия (на Бажова, гост. Исеть, Оперный театр)",  "Киностудия",  "*"),
        Transport( "https://mobile.ettu.ru/station/3702",  "Кирова (на Крылова)",  "Кирова",  "*"),
        Transport( "https://mobile.ettu.ru/station/3960",  "Кирова (на ст. ВИЗ)",  "Кирова",  "*"),
        Transport( "https://mobile.ettu.ru/station/4107",  "Кирова (на Колмогорова)",  "Кирова",  "*"),
        Transport( "https://mobile.ettu.ru/station/3383",  "Кировградская (на Донбасскую)",  "Кировградская",  "*"),
        Transport( "https://mobile.ettu.ru/station/3384",  "Кировградская (на Уральских Рабочих)",  "Кировградская",  "*"),
        Transport( "https://mobile.ettu.ru/station/4284",  "Кишиневская (на Таганский ряд)",  "Кишиневская",  "*"),
        Transport( "https://mobile.ettu.ru/station/4285",  "Кишиневская (на ст. 7 Ключей)",  "Кишиневская",  "*"),
        Transport( "https://mobile.ettu.ru/station/3386",  "Колмогорова (на Таганский ряд)",  "Колмогорова",  "*"),
        Transport( "https://mobile.ettu.ru/station/4117",  "Колмогорова (на Кирова)",  "Колмогорова",  "*"),
        Transport( "https://mobile.ettu.ru/station/3387",  "Комсомольская (на Профессорскую)",  "Комсомольская",  "*"),
        Transport( "https://mobile.ettu.ru/station/3388",  "Комсомольская (на ст. 40 лет ВЛКСМ)",  "Комсомольская",  "*"),
        Transport( "https://mobile.ettu.ru/station/3529",  "Кондукторская (на Пионерскую)",  "Кондукторская",  "*"),
        Transport( "https://mobile.ettu.ru/station/3535",  "Кондукторская (на Блюхера)",  "Кондукторская",  "*"),
        Transport( "https://mobile.ettu.ru/station/963721",  "Красноуральская (на Заводскую)",  "Красноуральская",  "*"),
        Transport( "https://mobile.ettu.ru/station/963724",  "Красноуральская (на Слесарей)",  "Красноуральская",  "*"),
        Transport( "https://mobile.ettu.ru/station/963728",  "Красноуральская (на Уралкабель)",  "Красноуральская",  "*"),
        Transport( "https://mobile.ettu.ru/station/3389",  "Краснофлотцев (на Фронтовых Бригад)",  "Краснофлотцев",  "*"),
        Transport( "https://mobile.ettu.ru/station/3390",  "Краснофлотцев (на Энтузиастов)",  "Краснофлотцев",  "*"),
        Transport( "https://mobile.ettu.ru/station/3391",  "Крылова (на Верх-Исетский б-р)",  "Крылова",  "*"),
        Transport( "https://mobile.ettu.ru/station/3392",  "Крылова (на Кирова)",  "Крылова",  "*"),
        Transport( "https://mobile.ettu.ru/station/3393",  "Кузнецова (с ДК им. Лаврова на ст. пл. 1-й Пятилетки)",  "Кузнецова",  "*"),
        Transport( "https://mobile.ettu.ru/station/3394",  "Кузнецова (с м. Уралмаш на ст. пл. 1-й Пятилетки)",  "Кузнецова",  "*"),
        Transport( "https://mobile.ettu.ru/station/3395",  "Кузнецова (на ДК им. Лаврова)",  "Кузнецова",  "*"),
        Transport( "https://mobile.ettu.ru/station/961839",  "Кузнецова (на м. Уралмаш)",  "Кузнецова",  "*"),
        Transport( "https://mobile.ettu.ru/station/961849",  "Куйбышева (на Цирк, пл. Коммунаров)",  "Куйбышева",  "*"),
        Transport( "https://mobile.ettu.ru/station/961850",  "Куйбышева (на ст. Дворец Спорта)",  "Куйбышева",  "*"),
        Transport( "https://mobile.ettu.ru/station/963233",  "Кушвинская",  "Кушвинская",  "*"),
        Transport( "https://mobile.ettu.ru/station/3400",  "Лукиных (на  Библиотеку)",  "Лукиных",  "*"),
        Transport( "https://mobile.ettu.ru/station/3401",  "Лукиных (на Диагностический центр)",  "Лукиных",  "*"),
        Transport( "https://mobile.ettu.ru/station/3402",  "Лукиных (на Сварщиков)",  "Лукиных",  "*"),
        Transport( "https://mobile.ettu.ru/station/4353",  "Ляпустина (на ст. Керамическая)",  "Ляпустина",  "*"),
        Transport( "https://mobile.ettu.ru/station/4354",  "Ляпустина (на Ферганскую)",  "Ляпустина",  "*"),
        Transport( "https://mobile.ettu.ru/station/963621",  "Метро Ботаническая",  "М. Ботаническая",  "Ботаническая"),
        Transport( "https://mobile.ettu.ru/station/3405",  "Метро Уралмаш (на Кузнецова)",  "М. Уралмаш",  "Уралмаш"),
        Transport( "https://mobile.ettu.ru/station/3406",  "Метро Уралмаш (на Педагогический университет)",  "М. Уралмаш",  "Уралмаш"),
        Transport( "https://mobile.ettu.ru/station/4057",  "Малый конный (на ст. Зеленый остров)",  "Малый конный",  "*"),
        Transport( "https://mobile.ettu.ru/station/4064",  "Малый конный (на ст. ВИЗ)",  "Малый конный",  "*"),
        Transport( "https://mobile.ettu.ru/station/4278",  "Маневровая (на ст. 7 Ключей)",  "Маневровая",  "*"),
        Transport( "https://mobile.ettu.ru/station/4301",  "Маневровая (на Таганский ряд)",  "Маневровая",  "*"),
        Transport( "https://mobile.ettu.ru/station/3500",  "Машиностроителей",  "Машиностроителей",  "*"),
        Transport( "https://mobile.ettu.ru/station/963733",  "Мельникова (на Уралкабель)",  "Мельникова",  "*"),
        Transport( "https://mobile.ettu.ru/station/963734",  "Мельникова (на Вечный Огонь)",  "Мельникова",  "*"),
        Transport( "https://mobile.ettu.ru/station/4045",  "Металлургов (на ст. ВИЗ)",  "Металлургов",  "*"),
        Transport( "https://mobile.ettu.ru/station/4046",  "Металлургов (на Волгоградскую)",  "Металлургов",  "*"),
        Transport( "https://mobile.ettu.ru/station/3407",  "Мира (на Блюхера)",  "Мира",  "*"),
        Transport( "https://mobile.ettu.ru/station/3408",  "Мира (на ТК Современник)",  "Мира",  "*"),
        Transport( "https://mobile.ettu.ru/station/3409",  "Московская (на ст. Дворец Спорта)",  "Московская",  "*"),
        Transport( "https://mobile.ettu.ru/station/3410",  "Московская (на ТК Алатырь)",  "Московская",  "*"),
        Transport( "https://mobile.ettu.ru/station/3411",  "Московская (на Юго-Западную)",  "Московская",  "*"),
        Transport( "https://mobile.ettu.ru/station/3412",  "Московская (с ТК Алатырь на Цирк)",  "Московская",  "*"),
        Transport( "https://mobile.ettu.ru/station/961866",  "Московская (с Юго-Западной на Цирк)",  "Московская",  "*"),
        Transport( "https://mobile.ettu.ru/station/963698",  "Московская от ст. Дворец Спорта (со ст. Дворец Спорта на Цирк)",  "Московская от ст. ДС",  "*"),
        Transport( "https://mobile.ettu.ru/station/4349",  "Мусоргского (на ст. Керамическая)",  "Мусоргского",  "*"),
        Transport( "https://mobile.ettu.ru/station/4350",  "Мусоргского (на Эскадронную)",  "Мусоргского",  "*"),
        Transport( "https://mobile.ettu.ru/station/3414",  "Новгородцевой (на Каменные палатки)",  "Новгородцевой",  "*"),
        Transport( "https://mobile.ettu.ru/station/3415",  "Новгородцевой (на Сиреневый б-р)",  "Новгородцевой",  "*"),
        Transport( "https://mobile.ettu.ru/station/961851",  "Новомосковская (на ст. ВИЗ)",  "Новомосковская",  "*"),
        Transport( "https://mobile.ettu.ru/station/961852",  "Новомосковская (на Волгоградскую)",  "Новомосковская",  "*"),
        Transport( "https://mobile.ettu.ru/station/4347",  "Новосибирская (на ст. Керамическая)",  "Новосибирская",  "*"),
        Transport( "https://mobile.ettu.ru/station/4348",  "Новосибирская (на Ляпустина)",  "Новосибирская",  "*"),
        Transport( "https://mobile.ettu.ru/station/3416",  "Оперный театр (на пл. 1905 года)",  "Оперный театр",  "*"),
        Transport( "https://mobile.ettu.ru/station/3417",  "Оперный театр (на гост. Исеть, Бажова,  Дом Кино)",  "Оперный театр",  "*"),
        Transport( "https://mobile.ettu.ru/station/3418",  "Папанина (на Шейнкмана)",  "Папанина",  "*"),
        Transport( "https://mobile.ettu.ru/station/3419",  "Папанина (на Управление дороги)",  "Папанина",  "*"),
        Transport( "https://mobile.ettu.ru/station/3420",  "Педагогический университет (на м. Уралмаш)",  "Педагогический университет",  "Пед университет"),
        Transport( "https://mobile.ettu.ru/station/3421",  "Педагогический университет (на Пионерскую)",  "Педагогический университет",  "Пед университет"),
        Transport( "https://mobile.ettu.ru/station/3422",  "Педагогический университет (на Электриков)",  "Педагогический университет",  "Пед университет"),
        Transport( "https://mobile.ettu.ru/station/3423",  "Педагогический университет (с Электриков на Пионерскую)",  "Педагогический университет",  "Пед университет"),
        Transport( "https://mobile.ettu.ru/station/3356",  "Пер. Рижский (на Завод РТИ)",  "Пер. Рижский",  "Переулок Рижевский"),
        Transport( "https://mobile.ettu.ru/station/3357",  "Пер. Рижский (на Ювелирную)",  "Пер. Рижский",  "Переулок Рижевский"),
        Transport( "https://mobile.ettu.ru/station/3424",  "Первомайская (на Блюхера)",  "Первомайская",  "*"),
        Transport( "https://mobile.ettu.ru/station/3425",  "Первомайская (на Уральский федеральный университет)",  "Первомайская",  "*"),
        Transport( "https://mobile.ettu.ru/station/4134",  "Пехотинцев (на Автомагистральную)",  "Пехотинцев",  "*"),
        Transport( "https://mobile.ettu.ru/station/4367",  "Пехотинцев (на Бебеля)",  "Пехотинцев",  "*"),
        Transport( "https://mobile.ettu.ru/station/3426",  "Пионерская (на 1-й км)",  "Пионерская",  "*"),
        Transport( "https://mobile.ettu.ru/station/3428",  "Пионерская (с 1-го км на Челюскинцев, Ж/д вокзал)",  "Пионерская",  "*"),
        Transport( "https://mobile.ettu.ru/station/3429",  "Пионерская (с Кондукторской на Челюскинцев, Ж/д вокзал)",  "Пионерская",  "*"),
        Transport( "https://mobile.ettu.ru/station/4192",  "Пионерская (на Кондукторскую)",  "Пионерская",  "*"),
        Transport( "https://mobile.ettu.ru/station/3430",  "Пл. 1905 г. (на гост. Исеть)",  "Пл. 1905 г",  "Площадь 1905"),
        Transport( "https://mobile.ettu.ru/station/3431",  "Пл. 1905 г. (на пл. Коммунаров)",  "Пл. 1905 г",  "Площадь 1905"),
        Transport( "https://mobile.ettu.ru/station/3501",  "Пл. 1-й Пятилетки",  "Пл. 1-й Пятилетки",  "Площадь первой Пятилетки"),
        Transport( "https://mobile.ettu.ru/station/963149",  "Пл. 1-й Пятилетки (на ст. пл. 1-й Пятилетки)",  "Пл. 1-й Пятилетки",  "Площадь первой Пятилетки"),
        Transport( "https://mobile.ettu.ru/station/3432",  "Пл. Коммунаров (на ТК Алатырь)",  "Пл. Коммунаров",  "Площадь Коммунаров"),
        Transport( "https://mobile.ettu.ru/station/3433",  "Пл. Коммунаров (с ТК Алатырь на Дворец Молодежи)",  "Площадь Коммунаровв",  "*"),
        Transport( "https://mobile.ettu.ru/station/3670",  "Пл. Коммунаров (на пл. 1905 г.)",  "Пл. Коммунаров",  "Площадь Коммунаров"),
        Transport( "https://mobile.ettu.ru/station/963739",  "Пл. Коммунаров (на Вечный Огонь)",  "Пл. Коммунаров",  "Площадь Коммунаров"),
        Transport( "https://mobile.ettu.ru/station/3434",  "Пл. Обороны (на Декабристов)",  "Пл. Обороны",  "Площадь Обороны"),
        Transport( "https://mobile.ettu.ru/station/3435",  "Пл. Обороны (на Тверитина)",  "Пл. Обороны",  "Площадь Обороны"),
        Transport( "https://mobile.ettu.ru/station/961844",  "Плотников (со ст. Зеленый остров на ст. ВИЗ)",  "Плотников",  "*"),
        Transport( "https://mobile.ettu.ru/station/4049",  "Плотников (на ст. Зеленый остров)",  "Плотников",  "*"),
        Transport( "https://mobile.ettu.ru/station/4078",  "Плотников (на Волгоградскую)",  "Плотников",  "*"),
        Transport( "https://mobile.ettu.ru/station/4079",  "Плотников (с Волгоградской на Металлургов)",  "Плотников",  "*"),
        Transport( "https://mobile.ettu.ru/station/961840",  "Победы (на Индустрии)",  "Победы",  "*"),
        Transport( "https://mobile.ettu.ru/station/4553",  "Победы (на Бакинских Комиссаров)",  "Победы",  "*"),
        Transport( "https://mobile.ettu.ru/station/4252",  "Посадская (на Цирк, пл. Коммунаров)",  "Посадская",  "*"),
        Transport( "https://mobile.ettu.ru/station/4253",  "Посадская (на ст. Дворец Спорта)",  "Посадская",  "*"),
        Transport( "https://mobile.ettu.ru/station/3440",  "Протезно-ортопедическое предприятие (на Челюскинцев)",  "Протезно-ортопедическое предприятие",  "*"),
        Transport( "https://mobile.ettu.ru/station/3441",  "Протезно-ортопедическое предприятие (на Шевченко)",  "Протезно-ортопедическое предприятие",  "*"),
        Transport( "https://mobile.ettu.ru/station/3442",  "Профессорская (на Гагарина)",  "Профессорская",  "*"),
        Transport( "https://mobile.ettu.ru/station/3443",  "Профессорская (на Комсомольскую)",  "Профессорская",  "*"),
        Transport( "https://mobile.ettu.ru/station/4050",  "Рабочих (на ст. Зеленый остров)",  "Рабочих",  "*"),
        Transport( "https://mobile.ettu.ru/station/4071",  "Рабочих (на ст. ВИЗ)",  "Рабочих",  "*"),
        Transport( "https://mobile.ettu.ru/station/3444",  "Радищева (на Московскую)",  "Радищева",  "*"),
        Transport( "https://mobile.ettu.ru/station/3445",  "Радищева (на Цирк)",  "Радищева",  "*"),
        Transport( "https://mobile.ettu.ru/station/4052",  "Разъезд (на ст. Зеленый остров)",  "Разъезд",  "*"),
        Transport( "https://mobile.ettu.ru/station/4069",  "Разъезд (на ст. ВИЗ)",  "Разъезд",  "*"),
        Transport( "https://mobile.ettu.ru/station/4282",  "Расточная (на ст. 7 Ключей)",  "Расточная",  "*"),
        Transport( "https://mobile.ettu.ru/station/4283",  "Расточная (на Таганский ряд)",  "Расточная",  "*"),
        Transport( "https://mobile.ettu.ru/station/3448",  "Сакко и Ванцетти (на пл. Коммунаров)",  "Сакко и Ванцетти",  "*"),
        Transport( "https://mobile.ettu.ru/station/3449",  "Сахалинская (на Студенческую)",  "Сахалинская",  "*"),
        Transport( "https://mobile.ettu.ru/station/3450",  "Сахалинская (на ст. Шарташ)",  "Сахалинская",  "*"),
        Transport( "https://mobile.ettu.ru/station/3451",  "Сварщиков (на Автомагистральную)",  "Сварщиков",  "*"),
        Transport( "https://mobile.ettu.ru/station/3452",  "Сварщиков (на Лукиных)",  "Сварщиков",  "*"),
        Transport( "https://mobile.ettu.ru/station/961845",  "Серафимы Дерябиной (на ст. ВИЗ)",  "Серафимы Дерябиной",  "*"),
        Transport( "https://mobile.ettu.ru/station/961846",  "Серафимы Дерябиной (на Волгоградскую)",  "Серафимы Дерябиной",  "*"),
        Transport( "https://mobile.ettu.ru/station/3455",  "Сиреневый б-р (на ст. 40 лет ВЛКСМ)",  "Сиреневый б-р",  "*"),
        Transport( "https://mobile.ettu.ru/station/3456",  "Сиреневый б-р (на Новгородцевой)",  "Сиреневый б-р",  "*"),
        Transport( "https://mobile.ettu.ru/station/3910",  "Слесарей (на ст. ВИЗ, Кирова)",  "Слесарей",  "*"),
        Transport( "https://mobile.ettu.ru/station/3525",  "Советская (на Пионерскую)",  "Советская",  "*"),
        Transport( "https://mobile.ettu.ru/station/3539",  "Советская (на Блюхера)",  "Советская",  "*"),
        Transport( "https://mobile.ettu.ru/station/3457",  "Студенческая (на ТК Современник)",  "Студенческая",  "*"),
        Transport( "https://mobile.ettu.ru/station/3458",  "Студенческая (на Сахалинскую)",  "Студенческая",  "*"),
        Transport( "https://mobile.ettu.ru/station/4305",  "Сухоложская (на ст. Вторчермет, ст. Керамическая)",  "Сухоложская",  "*"),
        Transport( "https://mobile.ettu.ru/station/4306",  "Сухоложская (на Братскую)",  "Сухоложская",  "*"),
        Transport( "https://mobile.ettu.ru/station/4237",  "Таганский ряд (со ст. 7 Ключей на Лукиных)",  "Таганский ряд",  "*"),
        Transport( "https://mobile.ettu.ru/station/4371",  "Таганский ряд (на ст. 7 Ключей)",  "Таганский ряд",  "*"),
        Transport( "https://mobile.ettu.ru/station/4372",  "Таганский ряд (с  ТРЦ Карнавал на Лукиных)",  "Таганский ряд",  "*"),
        Transport( "https://mobile.ettu.ru/station/4373",  "Таганский ряд (на ТРЦ Карнавал)",  "Таганский ряд",  "*"),
        Transport( "https://mobile.ettu.ru/station/3459",  "Татищева (на Заводскую)",  "Татищева",  "*"),
        Transport( "https://mobile.ettu.ru/station/3460",  "Татищева (на Волгоградскую, ст. Зеленый остров)",  "Татищева",  "*"),
        Transport( "https://mobile.ettu.ru/station/3947",  "Тверитина (на ст. ЦПКиО)",  "Тверитина",  "*"),
        Transport( "https://mobile.ettu.ru/station/3955",  "Тверитина (на Куйбышева-Луначарского)",  "Тверитина",  "*"),
        Transport( "https://mobile.ettu.ru/station/3438",  "Театр музыкальной комедии (на Оперный театр)",  "Театр муз комедии",  "*"),
        Transport( "https://mobile.ettu.ru/station/3439",  "Театр музыкальной комедии (на пл. 1905 г.)",  "Театр муз комедии",  "*"),
        Transport( "https://mobile.ettu.ru/station/4270",  "Теплоходный  пр. (на ст. 7 Ключей)",  "Теплоходный  пр.",  "Теплоходный  проспект"),
        Transport( "https://mobile.ettu.ru/station/4271",  "Теплоходный пр. (на Таганский ряд)",  "Теплоходный  пр.",  "Теплоходный  проспект"),
        Transport( "https://mobile.ettu.ru/station/4274",  "Техническая (на ст. 7 Ключей)",  "Техническая",  "*"),
        Transport( "https://mobile.ettu.ru/station/4277",  "Техническая (на Таганский ряд)",  "Техническая",  "*"),
        Transport( "https://mobile.ettu.ru/station/3461",  "Техучилище (на 1-й км)",  "Техучилище",  "*"),
        Transport( "https://mobile.ettu.ru/station/3462",  "Техучилище (на Калининскую)",  "Техучилище",  "*"),
        Transport( "https://mobile.ettu.ru/station/3374",  "ТК Буревестник (на Волгоградскую)",  "ТК Буревестник",  "Торговый Комплекс Буревестник"),
        Transport( "https://mobile.ettu.ru/station/3375",  "ТК Буревестник (на Московскую)",  "ТК Буревестник",  "Торговый Комплекс Буревестник"),
        Transport( "https://mobile.ettu.ru/station/3376",  "ТК Современник (на Мира)",  "ТК Современник",  "Торговый Комплекс Современник"),
        Transport( "https://mobile.ettu.ru/station/961843",  "ТК Современник (на Студенческую)",  "ТК Современник",  "Торговый Комплекс Современник"),
        Transport( "https://mobile.ettu.ru/station/3334",  "ТРЦ Карнавал (на Верх-Исетский рынок)",  "ТРЦ Карнавал",  "Торгово Развлекательный Центр Карнавал"),
        Transport( "https://mobile.ettu.ru/station/3335",  "ТРЦ Карнавал (на Таганский ряд)",  "ТРЦ Карнавал",  "Торгово Развлекательный Центр Карнавал"),
        Transport( "https://mobile.ettu.ru/station/3403",  "ТЦ Алатырь (на Московскую)",  "ТЦ Алатырь",  "Торговый Центр Алатырь"),
        Transport( "https://mobile.ettu.ru/station/3404",  "ТЦ Алатырь (на пл. Коммунаров)",  "ТЦ Алатырь",  "Торговый Центр Алатырь"),
        Transport( "https://mobile.ettu.ru/station/3465",  "Управление дороги (на Ельцина)",  "Управление дороги",  "*"),
        Transport( "https://mobile.ettu.ru/station/3466",  "Управление дороги (на Ж/д вокзал)",  "Управление дороги",  "*"),
        Transport( "https://mobile.ettu.ru/station/963731",  "Уралкабель (на Красноуральскую)",  "Уралкабель",  "*"),
        Transport( "https://mobile.ettu.ru/station/963732",  "Уралкабель (на Мельникова)",  "Уралкабель",  "*"),
        Transport( "https://mobile.ettu.ru/station/3463",  "Уральский федеральный университет (на Восточную)",  "УрФУ",  "УрФУ"),
        Transport( "https://mobile.ettu.ru/station/961904",  "Уральский федеральный университет (на Первомайскую)",  "УрФУ",  "УрФУ"),
        Transport( "https://mobile.ettu.ru/station/963284",  "Уральский федеральный университет (на Профессорскую)",  "УрФУ",  "УрФУ"),
        Transport( "https://mobile.ettu.ru/station/4174",  "Уральских Рабочих (на Бакинских Комиссаров)",  "Уральских Рабочих",  "*"),
        Transport( "https://mobile.ettu.ru/station/4175",  "Уральских Рабочих (на Кировградскую)",  "Уральских Рабочих",  "*"),
        Transport( "https://mobile.ettu.ru/station/4090",  "Ухтомская (на Серафимы Дерябиной)",  "Ухтомская",  "*"),
        Transport( "https://mobile.ettu.ru/station/4091",  "Ухтомская (на ст. ВИЗ)",  "Ухтомская",  "*"),
        Transport( "https://mobile.ettu.ru/station/3527",  "Учителей (на Кондукторскую)",  "Учителей",  "*"),
        Transport( "https://mobile.ettu.ru/station/961841",  "Учителей (на Блюхера)",  "Учителей",  "*"),
        Transport( "https://mobile.ettu.ru/station/3446",  "Фармацевтический колледж (на ТРЦ Карнавал)",  "Фармацевтический колледж",  "*"),
        Transport( "https://mobile.ettu.ru/station/3447",  "Фармацевтический колледж (на Таганский ряд)",  "Фармацевтический колледж",  "*"),
        Transport( "https://mobile.ettu.ru/station/4320",  "Ферганская (на Сухоложскую)",  "Ферганская",  "*"),
        Transport( "https://mobile.ettu.ru/station/4321",  "Ферганская (на ст. Керамическая)",  "Ферганская",  "*"),
        Transport( "https://mobile.ettu.ru/station/3502",  "Фрезеровщиков",  "Фрезеровщиков",  "*"),
        Transport( "https://mobile.ettu.ru/station/3467",  "Фронтовых Бригад (на Ворошиловскую)",  "Фронтовых Бригад",  "*"),
        Transport( "https://mobile.ettu.ru/station/3468",  "Фронтовых Бригад (на Краснофлотцев)",  "Фронтовых Бригад",  "*"),
        Transport( "https://mobile.ettu.ru/station/3469",  "Фрунзе (на Автовокзал)",  "Фрунзе",  "*"),
        Transport( "https://mobile.ettu.ru/station/3995",  "Фрунзе (на Большакова)",  "Фрунзе",  "*"),
        Transport( "https://mobile.ettu.ru/station/963680",  "Фучика (на Южную, Шварца)",  "Фучика",  "*"),
        Transport( "https://mobile.ettu.ru/station/963681",  "Фучика (на б-р Малахова)",  "Фучика",  "*"),
        Transport( "https://mobile.ettu.ru/station/3472",  "Цирк (на Белинского)",  "Цирк",  "*"),
        Transport( "https://mobile.ettu.ru/station/3473",  "Цирк (на Академию при Президенте России)",  "Цирк",  "*"),
        Transport( "https://mobile.ettu.ru/station/3474",  "Цирк (с Белинского на Радищева)",  "Цирк",  "*"),
        Transport( "https://mobile.ettu.ru/station/3475",  "Цирк (с Академии при Президенте России на Радищева)",  "Цирк",  "*"),
        Transport( "https://mobile.ettu.ru/station/3503",  "ЦПКиО",  "ЦПКиО",  "Центральный парк культуры и отдыха"),
        Transport( "https://mobile.ettu.ru/station/3476",  "Челюскинцев (на Ж/д вокзал, Пионерскую)",  "Челюскинцев",  "*"),
        Transport( "https://mobile.ettu.ru/station/3477",  "Челюскинцев (на Протезно-ортопедическое предприятие)",  "Челюскинцев",  "*"),
        Transport( "https://mobile.ettu.ru/station/3504",  "Шарташ",  "Шарташ",  "*"),
        Transport( "https://mobile.ettu.ru/station/3478",  "Шарташская (на гост. Исеть)",  "Шарташская",  "*"),
        Transport( "https://mobile.ettu.ru/station/3479",  "Шарташская (на Шевченко)",  "Шарташская",  "*"),
        Transport( "https://mobile.ettu.ru/station/3330",  "Шварца (на Ювелирную)",  "Шварца",  "*"),
        Transport( "https://mobile.ettu.ru/station/3331",  "Шварца (на Южную, Фучика)",  "Шварца",  "*"),
        Transport( "https://mobile.ettu.ru/station/3480",  "Шевченко (на Протезно-ортопедическое предприятие)",  "Шевченко",  "*"),
        Transport( "https://mobile.ettu.ru/station/3481",  "Шевченко (на Шарташскую)",  "Шевченко",  "*"),
        Transport( "https://mobile.ettu.ru/station/3482",  "Шейнкмана (на Дворец Молодежи)",  "Шейнкмана",  "*"),
        Transport( "https://mobile.ettu.ru/station/3483",  "Шейнкмана (на Папанина)",  "Шейнкмана",  "*"),
        Transport( "https://mobile.ettu.ru/station/4296",  "Школа им. С.В. Рахманинова (на ст. 7 Ключей)",  "Школа им. С.В. Рахманинова",  "*"),
        Transport( "https://mobile.ettu.ru/station/4297",  "Школа им. С.В. Рахманинова (на Таганский ряд)",  "Школа им. С.В. Рахманинова",  "*"),
        Transport( "https://mobile.ettu.ru/station/3484",  "Электриков (на Ворошиловскую)",  "Электриков",  "*"),
        Transport( "https://mobile.ettu.ru/station/3485",  "Электриков (на Педагогический университет)",  "Электриков",  "*"),
        Transport( "https://mobile.ettu.ru/station/3505",  "Эльмаш",  "Эльмаш",  "*"),
        Transport( "https://mobile.ettu.ru/station/3486",  "Энтузиастов (с Краснофлотцев на ст. Эльмаш, ст. Фрезеровщиков)",  "Энтузиастов",  "*"),
        Transport( "https://mobile.ettu.ru/station/3487",  "Энтузиастов (со ст. Фрезеровщиков на Краснофлотцев)",  "Энтузиастов",  "*"),
        Transport( "https://mobile.ettu.ru/station/3488",  "Энтузиастов (со ст. Эльмаш на Краснофлотцев)",  "Энтузиастов",  "*"),
        Transport( "https://mobile.ettu.ru/station/4351",  "Эскадронная (на ст. Керамическая)",  "Эскадронная",  "*"),
        Transport( "https://mobile.ettu.ru/station/4352",  "Эскадронная (на Ляпустина)",  "Эскадронная",  "*"),
        Transport( "https://mobile.ettu.ru/station/3489",  "Ювелирная (на Шварца)",  "Ювелирная",  "*"),
        Transport( "https://mobile.ettu.ru/station/3490",  "Ювелирная (на пер. Рижский)",  "Ювелирная",  "*"),
        Transport( "https://mobile.ettu.ru/station/3983",  "Юго-Западная (на Белореченскую)",  "Юго-Западная",  "*"),
        Transport( "https://mobile.ettu.ru/station/3984",  "Юго-Западная (на Московскую)",  "Юго-Западная",  "*"),
        Transport( "https://mobile.ettu.ru/station/3491",  "Южная (на Автовокзал)",  "Южная",  "*"),
        Transport( "https://mobile.ettu.ru/station/3492",  "Южная (на Шварца, Фучика)",  "Южная",  "*"),
        Transport( "https://mobile.ettu.ru/station/3496",  "Южная (конечная)",  "Южная",  "*"))


    val dataBus = arrayListOf<Transport>(
        Transport( "https://mobile.ettu.ru/station/962064",  "1-й км (на Техучилище)",  "1-й км",  "Первый километр"),
        Transport( "https://mobile.ettu.ru/station/962097",  "1-й км (на Ж/д вокзал, Пионерскую)",  "1-й км",  "Первый километр"),
        Transport( "https://mobile.ettu.ru/station/962946",  "40 лет Октября (на Хмелева)",  "40 лет Октября",  "Сорок лет Октября"),
        Transport( "https://mobile.ettu.ru/station/961943",  "Авиационная (на Саввы Белых)",  "Авиационная",  "*"),
        Transport( "https://mobile.ettu.ru/station/962910",  "Авиационная (на Щорса)",  "Авиационная",  "*"),
        Transport( "https://mobile.ettu.ru/station/962386",  "Автовокзал (на Серова)",  "Автовокзал",  "*"),
        Transport( "https://mobile.ettu.ru/station/962435",  "Автовокзал (на Щорса)",  "Автовокзал",  "*"),
        Transport( "https://mobile.ettu.ru/station/961914",  "Азина (на Дом Музыки)",  "Азина",  "*"),
        Transport( "https://mobile.ettu.ru/station/962520",  "Академгородок",  "Академгородок",  "*"),
        Transport( "https://mobile.ettu.ru/station/962419",  "Академика Вонсовского (на Начдива Онуфриева)",  "Академика Вонсовского",  "*"),
        Transport( "https://mobile.ettu.ru/station/962796",  "Академика Вонсовского (на Рабочую)",  "Академика Вонсовского",  "*"),
        Transport( "https://mobile.ettu.ru/station/962324",  "Академическая (на Мира)",  "Академическая",  "*"),
        Transport( "https://mobile.ettu.ru/station/962875",  "Академическая",  "Академическая",  "*"),
        Transport( "https://mobile.ettu.ru/station/962939",  "Академическая (на ТК Современник)",  "Академическая",  "*"),
        Transport( "https://mobile.ettu.ru/station/962399",  "Амундсена (на Начдива Онуфриева)",  "Амундсена",  "*"),
        Transport( "https://mobile.ettu.ru/station/962427",  "Амундсена (на Волгоградскую)",  "Амундсена",  "*"),
        Transport( "https://mobile.ettu.ru/station/962790",  "Амундсена (на пр-д Решетникова)",  "Амундсена",  "*"),
        Transport( "https://mobile.ettu.ru/station/962010",  "Артиллерийский институт (на Прониной)",  "Артиллерийский институт",  "*"),
        Transport( "https://mobile.ettu.ru/station/962806",  "Артиллерийский институт (на Садовую)",  "Артиллерийский институт",  "*"),
        Transport( "https://mobile.ettu.ru/station/962045",  "Архитектурная академия (на ТЮЗ)",  "Архитектурная академия",  "*"),
        Transport( "https://mobile.ettu.ru/station/961922",  "Архитектурная академия (на пр. Ленина)",  "Архитектурная академия",  "*"),
        Transport( "https://mobile.ettu.ru/station/962618",  "Бакинских Комиссаров (на Ломоносова)",  "Бакинских Комиссаров",  "*"),
        Transport( "https://mobile.ettu.ru/station/962988",  "Бакинских Комиссаров (на ст. Коммунистическая)",  "Бакинских Комиссаров",  "*"),
        Transport( "https://mobile.ettu.ru/station/962696",  "Баумана (на Красных Командиров)",  "Баумана",  "*"),
        Transport( "https://mobile.ettu.ru/station/962372",  "Белореченская (на ст. Посадская)",  "Белореченская",  "*"),
        Transport( "https://mobile.ettu.ru/station/962376",  "Белореченская (на Гурзуфскую)",  "Белореченская",  "*"),
        Transport( "https://mobile.ettu.ru/station/962653",  "Библиотека (на Краснознаменную)",  "Библиотека",  "*"),
        Transport( "https://mobile.ettu.ru/station/962794",  "Библиотека им. Белинского (на Дом Кино, пр. Ленина)",  "Библиотека им. Белинского",  "*"),
        Transport( "https://mobile.ettu.ru/station/962832",  "Библиотека им. Крапивина (на Советскую)",  "Библиотека им. Крапивина",  "*"),
        Transport( "https://mobile.ettu.ru/station/962833",  "Библиотека им. Крапивина (на Луначарского)",  "Библиотека им. Крапивина",  "*"),
        Transport( "https://mobile.ettu.ru/station/962793",  "Большакова (на Декабристов)",  "Большакова",  "*"),
        Transport( "https://mobile.ettu.ru/station/962134",  "Боровая (на ТК Современник)",  "Боровая",  "*"),
        Transport( "https://mobile.ettu.ru/station/962337",  "Боровая (на Менделеева)",  "Боровая",  "*"),
        Transport( "https://mobile.ettu.ru/station/961979",  "Бородина (на Инженерную)",  "Боровая",  "*"),
        Transport( "https://mobile.ettu.ru/station/961994",  "Бородина (на ДК Химмаш)",  "Боровая",  "*"),
        Transport( "https://mobile.ettu.ru/station/962475",  "Ботаническая",  "Ботаническая",  "*"),
        Transport( "https://mobile.ettu.ru/station/962638",  "Б-р Культуры (на пр. Орджоникидзе)",  "Б-р Культуры",  "Бульвар Культуры"),
        Transport( "https://mobile.ettu.ru/station/962472",  "Б-р Малахова (на ст. Ботаническая)",  "Б-р Малахова",  "Бульвар Малахова"),
        Transport( "https://mobile.ettu.ru/station/962479",  "Б-р Малахова (на Тбилисский б-р)",  "Б-р Малахова",  "Бульвар Малахова"),
        Transport( "https://mobile.ettu.ru/station/962581",  "Веер (на Ломоносова)",  "Веер",  "*"),
        Transport( "https://mobile.ettu.ru/station/962942",  "Веер (на Ярославскую)",  "Веер",  "*"),
        Transport( "https://mobile.ettu.ru/station/962202",  "Викулова (на Крауля)",  "Викулова",  "*"),
        Transport( "https://mobile.ettu.ru/station/962218",  "Викулова (на Заводскую)",  "Викулова",  "*"),
        Transport( "https://mobile.ettu.ru/station/962739",  "Войкова (на Красных Командиров)",  "Войкова",  "*"),
        Transport( "https://mobile.ettu.ru/station/962395",  "Волгоградская (на Амундсена)",  "Волгоградская",  "*"),
        Transport( "https://mobile.ettu.ru/station/962792",  "Волгоградская (на Шаумяна)",  "Волгоградская",  "*"),
        Transport( "https://mobile.ettu.ru/station/962707",  "Ворошиловская (на Фронтовых Бригад)",  "Ворошиловская",  "*"),
        Transport( "https://mobile.ettu.ru/station/962721",  "Ворошиловская (на Электриков)",  "Ворошиловская",  "*"),
        Transport( "https://mobile.ettu.ru/station/962659",  "Восстания (на Стахановскую)",  "Восстания",  "*"),
        Transport( "https://mobile.ettu.ru/station/962943",  "Восстания (на Ломоносова)",  "Восстания",  "*"),
        Transport( "https://mobile.ettu.ru/station/962944",  "Восстания (на Победы)",  "Восстания",  "*"),
        Transport( "https://mobile.ettu.ru/station/962156",  "Гагарина (на Генеральскую)",  "Гагарина",  "*"),
        Transport( "https://mobile.ettu.ru/station/962309",  "Гагарина (на Профессорскую)",  "Гагарина",  "*"),
        Transport( "https://mobile.ettu.ru/station/962152",  "Генеральская (на Трансагентство)",  "Генеральская",  "*"),
        Transport( "https://mobile.ettu.ru/station/962927",  "Генеральская (на Гагарина)",  "Генеральская",  "*"),
        Transport( "https://mobile.ettu.ru/station/962803",  "Гончарный (на Уктус)",  "Гончарный",  "*"),
        Transport( "https://mobile.ettu.ru/station/962175",  "Горького (на Храм Большой Златоуст)",  "Горького",  "*"),
        Transport( "https://mobile.ettu.ru/station/962367",  "Гурзуфская (на Белореченскую)",  "Гурзуфская",  "*"),
        Transport( "https://mobile.ettu.ru/station/962380",  "Гурзуфская (на Репина)",  "Гурзуфская",  "*"),
        Transport( "https://mobile.ettu.ru/station/961985",  "Дагестанская (на ст. Химмаш)",  "Дагестанская",  "*"),
        Transport( "https://mobile.ettu.ru/station/962335",  "Данилы Зверева (на Боровую)",  "Данилы Зверева",  "*"),
        Transport( "https://mobile.ettu.ru/station/962033",  "Декабристов (на Куйбышева)",  "Декабристов",  "*"),
        Transport( "https://mobile.ettu.ru/station/962795",  "Декабристов (с Большакова на Чапаева)",  "Декабристов",  "*"),
        Transport( "https://mobile.ettu.ru/station/962631",  "Детская больница (на пл. 1-й Пятилетки)",  "Детская больница",  "*"),
        Transport( "https://mobile.ettu.ru/station/962897",  "Димитрова (на Косарева)",  "Димитрова",  "*"),
        Transport( "https://mobile.ettu.ru/station/962053",  "ДК железнодорожников (на ст. Ж/д вокзал, ст. Академическая, ст. Коммунистическая)",  "ДК железнодорожников",  "Дворец Культуры железнодорожников"),
        Transport( "https://mobile.ettu.ru/station/962550",  "ДК им. Лаврова (на Фрезеровщиков)",  "ДК им. Лаврова",  "Дворец Культуры им. Лаврова"),
        Transport( "https://mobile.ettu.ru/station/962596",  "ДК им. Лаврова (на м. Уралмаш)",  "ДК им. Лаврова",  "Дворец Культуры им. Лаврова"),
        Transport( "https://mobile.ettu.ru/station/962898",  "ДК Химмаш (на Бородина)",  "ДК Химмаш",  "Дворец Культуры Химмаш"),
        Transport( "https://mobile.ettu.ru/station/962900",  "ДК Химмаш (на Димитрова)",  "ДК Химмаш",  "Дворец Культуры Химмаш"),
        Transport( "https://mobile.ettu.ru/station/962149",  "Дом Кино (на Горького, ст. Ж/д вокзал, ст. Химмаш)",  "Дом Кино",  "*"),
        Transport( "https://mobile.ettu.ru/station/962292",  "Дом Кино (на Трансагентство)",  "Дом Кино",  "*"),
        Transport( "https://mobile.ettu.ru/station/962114",  "Дом Музыки (на ДК железнодорожников)",  "Дом Музыки",  "*"),
        Transport( "https://mobile.ettu.ru/station/961915",  "Дом Музыки (на ТЮЗ)",  "Дом Музыки",  "Дом Музыки"),
        Transport( "https://mobile.ettu.ru/station/962647",  "Дом Пионеров (на пр. Орджоникидзе)",  "Дом Пионеров",  "*"),
        Transport( "https://mobile.ettu.ru/station/962062",  "Ж/д вокзал (на Азина)",  "Ж/д вокзал",  "Жд вокзал"),
        Transport( "https://mobile.ettu.ru/station/961905",  "Ж/д вокзал (1, 9 маршруты)",  "Ж/д вокзал",  "Жд вокзал"),
        Transport( "https://mobile.ettu.ru/station/962867",  "Ж/д вокзал (11 маршрут)",  "Ж/д вокзал",  "Жд вокзал"),
        Transport( "https://mobile.ettu.ru/station/962200",  "Заводская (на Викулова)",  "Заводская",  "*"),
        Transport( "https://mobile.ettu.ru/station/962220",  "Заводская (на Токарей)",  "Заводская",  "*"),
        Transport( "https://mobile.ettu.ru/station/962690",  "Ильича (на м. пр. Космонавтов)",  "Ильича",  "*"),
        Transport( "https://mobile.ettu.ru/station/962691",  "Ильича",  "Ильича",  "*"),
        Transport( "https://mobile.ettu.ru/station/962556",  "Индустрии (на Ломоносова)",  "Индустрии",  "*"),
        Transport( "https://mobile.ettu.ru/station/962588",  "Индустрии (на Фрезеровщиков)",  "Индустрии",  "*"),
        Transport( "https://mobile.ettu.ru/station/962658",  "Индустрии (на Ильича)",  "Индустрии",  "*"),
        Transport( "https://mobile.ettu.ru/station/961970",  "Инженера Алиева (на Димитрова)",  "Инженера Алиева",  "*"),
        Transport( "https://mobile.ettu.ru/station/962901",  "Инженера Алиева (на Нижнеисетск)",  "Инженера Алиева",  "*"),
        Transport( "https://mobile.ettu.ru/station/961982",  "Инженерная (на Дагестанскую)",  "Инженерная",  "*"),
        Transport( "https://mobile.ettu.ru/station/962899",  "Инженерная (на Бородина)",  "Инженерная",  "*"),
        Transport( "https://mobile.ettu.ru/station/962018",  "Институт дерматологии (на Самолетную)",  "Институт дерматологии",  "*"),
        Transport( "https://mobile.ettu.ru/station/962802",  "Институт дерматологии (на Гончарный)",  "Институт дерматологии",  "*"),
        Transport( "https://mobile.ettu.ru/station/962196",  "Институт связи (на Токарей)",  "Институт связи",  "*"),
        Transport( "https://mobile.ettu.ru/station/962234",  "Институт связи (на Центральный стадион)",  "Институт связи",  "*"),
        Transport( "https://mobile.ettu.ru/station/963003",  "Институт связи (на Гурзуфскую)",  "Институт связи",  "*"),
        Transport( "https://mobile.ettu.ru/station/962840",  "Июльская (на Парковый пер.)",  "Июльская",  "*"),
        Transport( "https://mobile.ettu.ru/station/962921",  "Июльская (на ст. Сулимова)",  "Июльская",  "*"),
        Transport( "https://mobile.ettu.ru/station/962613",  "Калинина (на Победы)",  "Калинина",  "*"),
        Transport( "https://mobile.ettu.ru/station/962627",  "Калинина (на Детскую больницу)",  "Калинина",  "*"),
        Transport( "https://mobile.ettu.ru/station/962067",  "Калининская (на Педагогический университет)",  "Калининская",  "*"),
        Transport( "https://mobile.ettu.ru/station/962093",  "Калининская (на Техучилище)",  "Калининская",  "*"),
        Transport( "https://mobile.ettu.ru/station/963778",  "Каменный ручей (на Прониной)",  "Каменный ручей",  "*"),
        Transport( "https://mobile.ettu.ru/station/962092",  "Карла Маркса (на Библиотеку им. Белинского)",  "Карла Маркса",  "*"),
        Transport( "https://mobile.ettu.ru/station/962501",  "Кварцевая (на ст. Табачная фабрика Альвис)",  "Кварцевая",  "*"),
        Transport( "https://mobile.ettu.ru/station/962512",  "Кварцевая (на Павлодарскую)",  "Кварцевая",  "*"),
        Transport( "https://mobile.ettu.ru/station/963024",  "Коммунистическая",  "Коммунистическая",  "*"),
        Transport( "https://mobile.ettu.ru/station/961976",  "Косарева (на ДК Химмаш)",  "Косарева",  "*"),
        Transport( "https://mobile.ettu.ru/station/962651",  "Краснознаменная (на пл. 1-й Пятилетки)",  "Краснознаменная",  "*"),
        Transport( "https://mobile.ettu.ru/station/962072",  "Краснофлотцев (с Педагогического университета на м. Уралмаш)",  "Краснофлотцев",  "*"),
        Transport( "https://mobile.ettu.ru/station/962703",  "Краснофлотцев (на Краснофлотцев)",  "Краснофлотцев",  "*"),
        Transport( "https://mobile.ettu.ru/station/962726",  "Краснофлотцев (на Фронтовых Бригад)",  "Краснофлотцев",  "*"),
        Transport( "https://mobile.ettu.ru/station/962742",  "Краснофлотцев (на Шефскую)",  "Краснофлотцев",  "*"),
        Transport( "https://mobile.ettu.ru/station/962693",  "Красных Командиров (на ст. Таганская)",  "Красных Командиров",  "*"),
        Transport( "https://mobile.ettu.ru/station/962737",  "Красных Командиров (на Спортивную)",  "Красных Командиров",  "*"),
        Transport( "https://mobile.ettu.ru/station/962207",  "Крауля (на ст. Крауля)",  "Крауля",  "*"),
        Transport( "https://mobile.ettu.ru/station/962208",  "Крауля",  "Крауля",  "*"),
        Transport( "https://mobile.ettu.ru/station/963009",  "Крауля (на ст.Крауля(по требованию)",  "Крауля",  "*"),
        Transport( "https://mobile.ettu.ru/station/962911",  "Крестинского (на Родонитовую)",  "Крестинского",  "*"),
        Transport( "https://mobile.ettu.ru/station/962912",  "Крестинского (на Шварца)",  "Крестинского",  "*"),
        Transport( "https://mobile.ettu.ru/station/962034",  "Куйбышева (на Карла Маркса)",  "Куйбышева",  "*"),
        Transport( "https://mobile.ettu.ru/station/961931",  "Куйбышева (на Декабристов)",  "Куйбышева",  "*"),
        Transport( "https://mobile.ettu.ru/station/962417",  "Лесная (на Рабочую)",  "Лесная",  "*"),
        Transport( "https://mobile.ettu.ru/station/962797",  "Лесная (на ТК Академический)",  "Лесная",  "*"),
        Transport( "https://mobile.ettu.ru/station/962557",  "Ломоносова (на Веер)",  "Ломоносова",  "*"),
        Transport( "https://mobile.ettu.ru/station/962584",  "Ломоносова (на Индустрии)",  "Ломоносова",  "*"),
        Transport( "https://mobile.ettu.ru/station/962607",  "Ломоносова (на Бакинских Комиссаров)",  "Ломоносова",  "*"),
        Transport( "https://mobile.ettu.ru/station/962621",  "Ломоносова (на Восстания)",  "Ломоносова",  "*"),
        Transport( "https://mobile.ettu.ru/station/962827",  "Луначарского (на ТЮЗ)",  "Луначарского",  "*"),
        Transport( "https://mobile.ettu.ru/station/962920",  "Луначарского (на Библиотеку им. Крапивина)",  "Луначарского",  "*"),
        Transport( "https://mobile.ettu.ru/station/962818",  "Метро Динамо (на ТЮЗ)",  "М. Динамо",  "Динамо"),
        Transport( "https://mobile.ettu.ru/station/962919",  "Метро Динамо",  "М. Динамо",  "Динамо"),
        Transport( "https://mobile.ettu.ru/station/962668",  "Метро пр. Космонавтов (на Стахановскую)",  "М. пр. Космонавтов",  "Проскпект Космонавтов"),
        Transport( "https://mobile.ettu.ru/station/962687",  "Метро пр. Космонавтов (на Старых Большевиков)",  "М. пр. Космонавтов",  "Проскпект Космонавтов"),
        Transport( "https://mobile.ettu.ru/station/962076",  "Метро Уралмаш (на ст. пл. 1-й Пятилетки)",  "М. Уралмаш",  "Уралмаш"),
        Transport( "https://mobile.ettu.ru/station/962088",  "Метро Уралмаш (на Педагогический университет)",  "М. Уралмаш",  "Уралмаш"),
        Transport( "https://mobile.ettu.ru/station/962548",  "Метро Уралмаш (на ДК им. Лаврова)",  "М. Уралмаш",  "Уралмаш"),
        Transport( "https://mobile.ettu.ru/station/962492",  "Межевая (на Павлодарскую)",  "Межевая",  "*"),
        Transport( "https://mobile.ettu.ru/station/962131",  "Менделеева (на Боровую)",  "Менделеева",  "*"),
        Transport( "https://mobile.ettu.ru/station/962339",  "Менделеева (на Парк Хаус)",  "Менделеева",  "*"),
        Transport( "https://mobile.ettu.ru/station/962414",  "Микрорайон (на ТК Академический)",  "Микрорайон",  "*"),
        Transport( "https://mobile.ettu.ru/station/962995",  "Микрорайон (на ст. Академгородок)",  "Микрорайон",  "*"),
        Transport( "https://mobile.ettu.ru/station/962934",  "Мира (на Уральский федеральный университет, Софьи Ковалевской)",  "Мира",  "*"),
        Transport( "https://mobile.ettu.ru/station/962785",  "Музей Бажова (на Трамвайный парк)",  "Музей Бажова",  "*"),
        Transport( "https://mobile.ettu.ru/station/962401",  "Начдива Онуфриева (на Академика Вонсовского)",  "Начдива Онуфриева",  "*"),
        Transport( "https://mobile.ettu.ru/station/962425",  "Начдива Онуфриева (на Амундсена)",  "Начдива Онуфриева",  "*"),
        Transport( "https://mobile.ettu.ru/station/962456",  "Начдива Онуфриева (на Чкалова)",  "Начдива Онуфриева",  "*"),
        Transport( "https://mobile.ettu.ru/station/962461",  "Начдива Онуфриева",  "Начдива Онуфриева",  "*"),
        Transport( "https://mobile.ettu.ru/station/961969",  "Нижнеисетск (на Инженера Алиева)",  "Нижнеисетск",  "*"),
        Transport( "https://mobile.ettu.ru/station/962902",  "Нижнеисетск (на Опытную станцию садоводства)",  "Нижнеисетск",  "*"),
        Transport( "https://mobile.ettu.ru/station/961965",  "Опытная станция садоводства (на Нижнеисетск)",  "Опытная станция садоводства",  "*"),
        Transport( "https://mobile.ettu.ru/station/962903",  "Опытная станция садоводства (на Садовую)",  "Опытная станция садоводства",  "*"),
        Transport( "https://mobile.ettu.ru/station/962493",  "Павлодарская (на Кварцевую)",  "Павлодарская",  "*"),
        Transport( "https://mobile.ettu.ru/station/962513",  "Павлодарская (на Самолетную)",  "Павлодарская",  "*"),
        Transport( "https://mobile.ettu.ru/station/962130",  "Парк Хаус (на Менделеева)",  "Парк Хаус",  "*"),
        Transport( "https://mobile.ettu.ru/station/962343",  "Парк Хаус (на Уральскую)",  "Парк Хаус",  "*"),
        Transport( "https://mobile.ettu.ru/station/962453",  "Парк Чкалова (на ст. Начдива Онуфриева)",  "Парк Чкалова",  "*"),
        Transport( "https://mobile.ettu.ru/station/962001",  "Пархоменко (на Инженера Алиева)",  "Пархоменко",  "*"),
        Transport( "https://mobile.ettu.ru/station/962746",  "Педагогический университет",  "Педагогический университет",  "*"),
        Transport( "https://mobile.ettu.ru/station/962940",  "Педагогический университет (на Краснофлотцев)",  "Педагогический университет",  "Пед университет"),
        Transport( "https://mobile.ettu.ru/station/962941",  "Педагогический университет (на Калининскую)",  "Педагогический университет",  "Пед университет"),
        Transport( "https://mobile.ettu.ru/station/962837",  "Пер. Парковый (на Июльскую)",  "Пер. Парковый ",  "Переулок Парковый"),
        Transport( "https://mobile.ettu.ru/station/962841",  "Пер. Парковый (на Советскую)",  "Пер. Парковый ",  "Переулок Парковый"),
        Transport( "https://mobile.ettu.ru/station/962016",  "Пер. Широкий (на Институт дерматологии)",  "Пер. Широкий",  "Переулок Широкий"),
        Transport( "https://mobile.ettu.ru/station/962932",  "Первомайская (на Студенческую)",  "Первомайская",  "*"),
        Transport( "https://mobile.ettu.ru/station/962124",  "Пионерская (на Уральскую)",  "Пионерская",  "*"),
        Transport( "https://mobile.ettu.ru/station/962350",  "Пионерская (на Ж/д вокзал, 1-й км)",  "Пионерская",  "*"),
        Transport( "https://mobile.ettu.ru/station/962080",  "Пл. 1-й Пятилетки",  "Пл. 1-й Пятилетки",  "Площадь первой Пятилетки"),
        Transport( "https://mobile.ettu.ru/station/962881",  "Пл. 1-й Пятилетки (на Дом Пионеров)",  "Пл. 1-й Пятилетки",  "Площадь первой Пятилетки"),
        Transport( "https://mobile.ettu.ru/station/962882",  "Пл. 1-й Пятилетки (на Церковь Рождества Христова)",  "Пл. 1-й Пятилетки",  "Площадь первой Пятилетки"),
        Transport( "https://mobile.ettu.ru/station/962611",  "Победы (на Восстания)",  "Победы",  "*"),
        Transport( "https://mobile.ettu.ru/station/962626",  "Победы (на Калинина)",  "Победы",  "*"),
        Transport( "https://mobile.ettu.ru/station/962374",  "Посадская",  "Посадская",  "*"),
        Transport( "https://mobile.ettu.ru/station/961924",  "Пр. Ленина (на Горького, Центральную гост.)",  "Пр. Ленина",  "Проспект Ленина"),
        Transport( "https://mobile.ettu.ru/station/962782",  "Пр. Ленина (на Архитектурную академию)",  "Пр. Ленина",  "Проспект Ленина"),
        Transport( "https://mobile.ettu.ru/station/962640",  "Пр. Орджоникидзе (на Калинина 8 м-т)",  "Пр. Орджоникидзе",  "Проспект Орджоникидзе"),
        Transport( "https://mobile.ettu.ru/station/962649",  "Пр. Орджоникидзе (на Калинина 10 м-т)",  "Пр. Орджоникидзе",  "Проспект Орджоникидзе"),
        Transport( "https://mobile.ettu.ru/station/962446",  "Пр-д Решетникова (на Чкалова)",  "Пр-д Решетникова",  "Проезд Решетникова"),
        Transport( "https://mobile.ettu.ru/station/962462",  "Пр-д Решетникова (на Амундсена)",  "Пр-д Решетникова",  "Проезд Решетникова"),
        Transport( "https://mobile.ettu.ru/station/962805",  "Прониной (на Артиллерийский институт)",  "Прониной",  "*"),
        Transport( "https://mobile.ettu.ru/station/962905",  "Прониной (на Уктус)",  "Прониной",  "*"),
        Transport( "https://mobile.ettu.ru/station/962158",  "Профессорская (на Гагарина)",  "Профессорская",  "*"),
        Transport( "https://mobile.ettu.ru/station/962313",  "Профессорская (на Уральский федеральный университет)",  "Профессорская",  "*"),
        Transport( "https://mobile.ettu.ru/station/962407",  "Рабочая (на Лесную)",  "Рабочая",  "*"),
        Transport( "https://mobile.ettu.ru/station/962418",  "Рабочая (на Академика Вонсовского)",  "Рабочая",  "*"),
        Transport( "https://mobile.ettu.ru/station/962233",  "Репина (на Институт связи)",  "Репина",  "*"),
        Transport( "https://mobile.ettu.ru/station/962470",  "Родонитовая (на Тбилисский б-р)",  "Родонитовая",  "*"),
        Transport( "https://mobile.ettu.ru/station/962482",  "Родонитовая (на Крестинского)",  "Родонитовая",  "*"),
        Transport( "https://mobile.ettu.ru/station/962454",  "Рынок на Громова (на ст. Начдива Онуфриева)",  "Рынок на Громова",  "*"),
        Transport( "https://mobile.ettu.ru/station/962024",  "Саввы Белых (на Авиационную)",  "Саввы Белых",  "*"),
        Transport( "https://mobile.ettu.ru/station/962800",  "Саввы Белых (на ст. Химмаш, ст. Ботаническая)",  "Саввы Белых",  "*"),
        Transport( "https://mobile.ettu.ru/station/961963",  "Садовая (на Опытную станцию садоводства)",  "Садовая",  "*"),
        Transport( "https://mobile.ettu.ru/station/962904",  "Садовая (на Артиллерийский институт)",  "Садовая",  "*"),
        Transport( "https://mobile.ettu.ru/station/962020",  "Самолетная (на Шварца)",  "Самолетная",  "*"),
        Transport( "https://mobile.ettu.ru/station/962490",  "Самолетная (на Межевую)",  "Самолетная",  "*"),
        Transport( "https://mobile.ettu.ru/station/962496",  "Самолетная (с Павлодарской на Самолетную)",  "Самолетная",  "*"),
        Transport( "https://mobile.ettu.ru/station/962801",  "Самолетная (на Институт дерматологии)",  "Самолетная",  "*"),
        Transport( "https://mobile.ettu.ru/station/962432",  "Серова (на Автовокзал)",  "Серова",  "*"),
        Transport( "https://mobile.ettu.ru/station/962789",  "Серова (на Шаумяна)",  "Серова",  "*"),
        Transport( "https://mobile.ettu.ru/station/962834",  "Советская (на пер. Парковый)",  "Советская",  "*"),
        Transport( "https://mobile.ettu.ru/station/962842",  "Советская (на Библиотеку им. Крапивина)",  "Советская",  "*"),
        Transport( "https://mobile.ettu.ru/station/962323",  "Софьи Ковалевской (на Первомайскую)",  "Софьи Ковалевской",  "*"),
        Transport( "https://mobile.ettu.ru/station/962699",  "Спортивная (на Баумана)",  "Спортивная",  "*"),
        Transport( "https://mobile.ettu.ru/station/962734",  "Спортивная (на Шефскую)",  "Спортивная",  "*"),
        Transport( "https://mobile.ettu.ru/station/962684",  "Старых Большевиков (на Шефскую)",  "Старых Большевиков",  "*"),
        Transport( "https://mobile.ettu.ru/station/962665",  "Стахановская (на Восстания)",  "Стахановская",  "*"),
        Transport( "https://mobile.ettu.ru/station/962933",  "Студенческая (на ст. Академическая)",  "Студенческая",  "*"),
        Transport( "https://mobile.ettu.ru/station/962922",  "Сулимова",  "Сулимова",  "*"),
        Transport( "https://mobile.ettu.ru/station/962515",  "Табачная фабрика",  "Табачная фабрика",  "*"),
        Transport( "https://mobile.ettu.ru/station/962677",  "Таганская (на Шефскую)",  "Таганская",  "*"),
        Transport( "https://mobile.ettu.ru/station/962749",  "Таганская",  "Таганская",  "*"),
        Transport( "https://mobile.ettu.ru/station/962471",  "Тбилисский б-р (на б-р Малахова)",  "Тбилисский б-р",  "Тбилисский бульвар"),
        Transport( "https://mobile.ettu.ru/station/962481",  "Тбилисский б-р (на Родонитовую)",  "Тбилисский б-р",  "Тбилисский бульвар"),
        Transport( "https://mobile.ettu.ru/station/962181",  "Театр Волхонка (на ТЦ Алатырь)",  "Театр Волхонка",  "*"),
        Transport( "https://mobile.ettu.ru/station/962244",  "Театр Волхонка (на Храм Большой Златоуст)",  "Театр Волхонка",  "*"),
        Transport( "https://mobile.ettu.ru/station/962066",  "Техучилище (на Калининскую)",  "Техучилище",  "*"),
        Transport( "https://mobile.ettu.ru/station/962095",  "Техучилище (на 1-й км)",  "Техучилище",  "*"),
        Transport( "https://mobile.ettu.ru/station/962410",  "ТК Академический (на ст. Академгородок)",  "ТК Академический",  "Торговый Комплекс Академический"),
        Transport( "https://mobile.ettu.ru/station/962416",  "ТК Академический (на Лесную)",  "ТК Академический",  "Торговый Комплекс Академический"),
        Transport( "https://mobile.ettu.ru/station/962138",  "ТК Современник (на Академическую)",  "ТК Современник",  "Торговый Комплекс Современник"),
        Transport( "https://mobile.ettu.ru/station/962333",  "ТК Современник (на Данилы Зверева)",  "ТК Современник",  "Торговый Комплекс Современник"),
        Transport( "https://mobile.ettu.ru/station/962198",  "Токарей (на Заводскую)",  "Токарей",  "*"),
        Transport( "https://mobile.ettu.ru/station/962224",  "Токарей (на Институт связи)",  "Токарей",  "*"),
        Transport( "https://mobile.ettu.ru/station/962110",  "Трамвайный парк (на Фрунзе)",  "Трамвайный парк",  "*"),
        Transport( "https://mobile.ettu.ru/station/962150",  "Трансагентство (на Дом Кино)",  "Трансагентство",  "*"),
        Transport( "https://mobile.ettu.ru/station/962305",  "Трансагентство (на Генеральскую)",  "Трансагентство",  "*"),
        Transport( "https://mobile.ettu.ru/station/962183",  "ТЦ Алатырь (на Центральный стадион)",  "ТЦ Алатырь",  "Торговый Центр Алатырь"),
        Transport( "https://mobile.ettu.ru/station/962242",  "ТЦ Алатырь (на Театр Волхонка)",  "ТЦ Алатырь",  "Торговый Центр Алатырь"),
        Transport( "https://mobile.ettu.ru/station/962047",  "ТЮЗ (с Архитектурной академии на Дом Музыки)",  "ТЮЗ",  "*"),
        Transport( "https://mobile.ettu.ru/station/961920",  "ТЮЗ (на Архитектурную академию)",  "ТЮЗ",  "*"),
        Transport( "https://mobile.ettu.ru/station/962808",  "ТЮЗ (на ст. м. Динамо)",  "ТЮЗ",  "*"),
        Transport( "https://mobile.ettu.ru/station/962822",  "ТЮЗ (со ст. м. Динамо на Луначарского)",  "ТЮЗ",  "*"),
        Transport( "https://mobile.ettu.ru/station/962015",  "Уктус (на Гончарный)",  "Уктус",  "*"),
        Transport( "https://mobile.ettu.ru/station/961956",  "Уктус (на Каменный ручей)",  "Уктус",  "*"),
        Transport( "https://mobile.ettu.ru/station/962848",  "Уктус",  "Уктус",  "*"),
        Transport( "https://mobile.ettu.ru/station/962126",  "Уральская (на Парк Хаус)",  "Уральская",  "*"),
        Transport( "https://mobile.ettu.ru/station/962347",  "Уральская (на Пионерскую)",  "Уральская",  "*"),
        Transport( "https://mobile.ettu.ru/station/962173",  "Уральский федеральный университет (на Профессорскую)",  "УрФУ",  "УрФУ"),
        Transport( "https://mobile.ettu.ru/station/962314",  "Уральский федеральный университет (на Софьи Ковалевской)",  "УрФУ",  "УрФУ"),
        Transport( "https://mobile.ettu.ru/station/961928",  "Федерация профсоюзов (на Куйбышева)",  "Федерация профсоюзов",  "*"),
        Transport( "https://mobile.ettu.ru/station/962553",  "Фрезеровщиков (на Индустрии)",  "Фрезеровщиков",  "*"),
        Transport( "https://mobile.ettu.ru/station/962592",  "Фрезеровщиков (на ДК им. Лаврова)",  "Фрезеровщиков",  "*"),
        Transport( "https://mobile.ettu.ru/station/962671",  "Фрезеровщиков (с Шефской на м. пр. Космонавтов)",  "Фрезеровщиков",  "*"),
        Transport( "https://mobile.ettu.ru/station/962704",  "Фронтовых Бригад (на Краснофлотцев)",  "Фронтовых Бригад",  "*"),
        Transport( "https://mobile.ettu.ru/station/962722",  "Фронтовых Бригад (на Ворошиловскую)",  "Фронтовых Бригад",  "*"),
        Transport( "https://mobile.ettu.ru/station/962786",  "Фрунзе (на Щорса)",  "Фрунзе",  "*"),
        Transport( "https://mobile.ettu.ru/station/962998",  "Фрунзе (на Большакова)",  "Фрунзе",  "*"),
        Transport( "https://mobile.ettu.ru/station/961989",  "Химмаш",  "Химмаш",  "*"),
        Transport( "https://mobile.ettu.ru/station/962945",  "Хмелева (на б-р Культуры)",  "Хмелева",  "*"),
        Transport( "https://mobile.ettu.ru/station/962178",  "Храм Большой Златоуст (на Театр Волхонка)",  "Храм Большой Златоуст",  "*"),
        Transport( "https://mobile.ettu.ru/station/962247",  "Храм Большой Златоуст (на Центральную гост.)",  "Храм Большой Златоуст",  "*"),
        Transport( "https://mobile.ettu.ru/station/962251",  "Центральная гост. (на пр. Ленина, Дом Кино)",  "Центральная гост.",  "*"),
        Transport( "https://mobile.ettu.ru/station/962294",  "Центральная гост. (на Федерацию профсоюзов, Библиотеку им. Белинского)",  "Центральная гост.",  "*"),
        Transport( "https://mobile.ettu.ru/station/962188",  "Центральный стадион (на Институт связи)",  "Центральный стадион",  "*"),
        Transport( "https://mobile.ettu.ru/station/962236",  "Центральный стадион (на ТЦ Алатырь)",  "Центральный стадион",  "*"),
        Transport( "https://mobile.ettu.ru/station/962635",  "Церковь Рождества Христова (на 40 лет Октября)",  "Церковь Рождества Христова",  "*"),
        Transport( "https://mobile.ettu.ru/station/962442",  "ЦПКиО",  "ЦПКиО",  "Центральный Парк Культуры и Отдыха"),
        Transport( "https://mobile.ettu.ru/station/962784",  "Чапаева (на Музей Бажова)",  "Чкалова",  "*"),
        Transport( "https://mobile.ettu.ru/station/962452",  "Чкалова (на парк Чкалова)",  "Чкалова",  "*"),
        Transport( "https://mobile.ettu.ru/station/962791",  "Чкалова (на пр-д Решетникова)",  "Чкалова",  "*"),
        Transport( "https://mobile.ettu.ru/station/962392",  "Шаумяна (на Волгоградскую)",  "Шаумяна",  "*"),
        Transport( "https://mobile.ettu.ru/station/962431",  "Шаумяна (на Серова)",  "Шаумяна",  "*"),
        Transport( "https://mobile.ettu.ru/station/961948",  "Шварца (на Самолетную)",  "Шварца",  "*"),
        Transport( "https://mobile.ettu.ru/station/962909",  "Шварца (на Саввы Белых)",  "Шварца",  "*"),
        Transport( "https://mobile.ettu.ru/station/962674",  "Шефская (с Таганской на Фрезеровщиков)",  "Шефская",  "*"),
        Transport( "https://mobile.ettu.ru/station/962683",  "Шефская (со Старых Большевиков на ст. Таганская)",  "Шефская",  "*"),
        Transport( "https://mobile.ettu.ru/station/962700",  "Шефская (с Краснофлотцев на Спортивную)",  "Шефская",  "*"),
        Transport( "https://mobile.ettu.ru/station/962730",  "Шефская (со Спортивной на Краснофлотцев)",  "Шефская",  "*"),
        Transport( "https://mobile.ettu.ru/station/962655",  "Школа (на Библиотеку)",  "Школа",  "*"),
        Transport( "https://mobile.ettu.ru/station/962908",  "Щербакова (на ТРЦ Екатерининский)",  "Щербакова",  "*"),
        Transport( "https://mobile.ettu.ru/station/962768",  "Щорса (на Авиационную)",  "Щорса",  "*"),
        Transport( "https://mobile.ettu.ru/station/962771",  "Щорса (на Фрунзе)",  "Щорса",  "*"),
        Transport( "https://mobile.ettu.ru/station/962788",  "Щорса (на Автовокзал)",  "Щорса",  "*"),
        Transport( "https://mobile.ettu.ru/station/962799",  "Щорса (на ст. ЦПКиО)",  "Щорса",  "*"),
        Transport( "https://mobile.ettu.ru/station/962710",  "Электриков (на Ворошиловскую)",  "Электриков",  "*"),
        Transport( "https://mobile.ettu.ru/station/962718",  "Электриков (на ст. Педагогический университет)",  "Электриков",  "*"),
        Transport( "https://mobile.ettu.ru/station/962504",  "Южный пр. (на ст. Табачная фабрика)",  "Южный пр.",  "Южный проспект"),
        Transport( "https://mobile.ettu.ru/station/962526",  "Южный пр. (на Кварцевую)",  "Южный пр.",  "Южный проспект"),
        Transport( "https://mobile.ettu.ru/station/962563",  "Ярославская (на ст. Коммунистическая)",  "Ярославская",  "*"),
        Transport( "https://mobile.ettu.ru/station/962578",  "Ярославская (на Веер)",  "Ярославская",  "*"))

}